FROM node:16-alpine
WORKDIR /protrac/backend
COPY package.json ./
RUN npm install
COPY . .
ENV NODE_OPTIONS="--require ./bootstrap-fetch.js"
ENV DB_URL=${DB_URL}
ENV DB_DEVELOPMENT_URL=${DB_DEVELOPMENT_URL}
ENV PASSKEY=${PASSKEY}
ENV PORT=${PORT}
ENV EMAIL_HOST=${EMAIL_HOST}
ENV EMAIL_PORT=${EMAIL_PORT}
ENV EMAIL_SECURE=${EMAIL_SECURE}
ENV EMAIL_SERVICE=${EMAIL_SERVICE}
ENV EMAIL_USER=${EMAIL_USER}
ENV EMAIL_PASS=${EMAIL_PASS}


EXPOSE 8080
CMD ["npm", "start"]