name: Deploy to Hostinger VPS (Development)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            set -Eeuo pipefail

            cd ~/Protrac/bacKendSlnko
            git fetch origin development
            git checkout development
            git pull origin development

            # Ensure Docker network exists for inter-container DNS
            docker network create protrac_net 2>/dev/null || true

            # Recreate development API (reads .env.dev)
            docker stop prod_api_development || true
            docker rm   prod_api_development || true

            docker build -t prod_api_development .

            docker run -d --name prod_api_development \
              --env-file .env.dev \
              --network protrac_net \
              -p 5002:8080 \
              --restart unless-stopped \
              prod_api_development

            # Debug: confirm REDIS_URL inside the container points at dragonfly
            docker exec prod_api_development printenv REDIS_URL || true
          EOF
