name: Deploy to Hostinger VPS (Development)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            set -Eeuo pipefail

            cd ~/Protrac/bacKendSlnko
            git fetch origin development
            git checkout development
            git pull origin development

            # Ensure Docker network exists
            docker network create protrac_net 2>/dev/null || true

            # Ensure Dragonfly is up (uses docker-compose.yml in this dir)
            docker compose up -d dragonfly
            # quick health check
            docker exec dragonfly redis-cli -a CHANGE_ME_STRONG PING || true

            # Recreate development API (reads .env.dev)
            docker rm -f prod_api_development 2>/dev/null || true
            docker build -t prod_api_development .

            docker run -d --name prod_api_development \
              --env-file .env.dev \
              --network protrac_net \
              -p 5002:8080 \
              --restart unless-stopped \
              prod_api_development

            # Confirm API is pointing at the docker service name (not 127.0.0.1)
            echo "REDIS_URL inside container:"
            docker exec prod_api_development printenv REDIS_URL || true
          EOF
