name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            cd ~/Protrac/bacKendSlnko && git checkout staging
            git pull origin staging
            docker stop prod_api_staging || true
            docker rm prod_api_staging || true
            docker build -t prod_api_staging .
            docker run --name prod_api_staging -p 5001:8080 -d --env-file .env.prod prod_api_staging
          EOF
