name: Deploy to Hostinger VPS (Development)

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            set -e

            cd ~/Protrac/bacKendSlnko
            git checkout development
            git pull origin development

            # network
            docker network create protrac_net || true

            # redis (expose to host)
            docker rm -f protrac-redis || true
            docker run -d --name protrac-redis \
              --network protrac_net \
              -p 6379:6379 \
              -v protrac_redis:/data \
              --restart unless-stopped \
              redis:7-alpine --appendonly yes

            # env (force REDIS_URL to host's localhost)
            sed -i '/^REDIS_URL=/d' .env.dev || true
            echo 'REDIS_URL=redis://host.docker.internal:6379' >> .env.dev

            # api
            docker rm -f prod_api_development || true
            docker build -t prod_api_development .
            docker run -d --name prod_api_development \
              --env-file .env.dev \
              --network protrac_net \
              --add-host=host.docker.internal:host-gateway \
              -p 5002:8080 \
              --restart unless-stopped \
              prod_api_development
          EOF
