name: Deploy to Hostinger VPS (production)

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} << 'EOF'
            cd ~/Protrac/bacKendSlnko && git checkout production
            git pull origin production
            docker stop prod_api || true
            docker rm prod_api || true
            docker build -t prod_api .
            docker run --name prod_api -p 5000:8080 -d --env-file .env.prod prod_api
          EOF
